To use numpy need to import the numpy module as follows.

In [1]:
import numpy as np # naming import convention

## Basic operations and Universal Numpy Functions

All numpy arithmetic operates element wise and are much faster than if you did them in pure python.

### Scalar-array operations


In [3]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [4]:
a + 2.5

array([ 3.5,  4.5,  5.5,  6.5])

In [5]:
b = np.ones(4) + 1

In [6]:
b

array([ 2.,  2.,  2.,  2.])

In [7]:
a - b

array([-1.,  0.,  1.,  2.])

Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum. For more details on numpy function visit [here](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

In [8]:
np.random.seed(77)
tempData = np.random.randint(25,37, size=10)
tempData2 = np.random.randint(25.5,37.5, size=10)
tempData3 = np.random.randint(26.5,36.5, size=10)
data = np.array([tempData, tempData2, tempData3])

In [9]:
data

array([[32, 29, 29, 36, 30, 33, 25, 34, 32, 30],
       [28, 25, 36, 31, 29, 31, 29, 30, 35, 32],
       [29, 27, 27, 35, 32, 30, 31, 34, 27, 34]])

In [10]:
# Compute sum of all elements; 
np.sum(data)  

922

In [11]:
# Compute sum of each column; 
np.sum(data, axis=0)  

array([ 89,  81,  92, 102,  91,  94,  85,  98,  94,  96])

In [12]:
# Compute sum of each row; 
np.sum(data, axis=1) 

array([310, 306, 306])

In [13]:
#Calculate the n-th discrete difference
np.diff(data)

array([[-3,  0,  7, -6,  3, -8,  9, -2, -2],
       [-3, 11, -5, -2,  2, -2,  1,  5, -3],
       [-2,  0,  8, -3, -2,  1,  3, -7,  7]])

In [14]:
# Computing mean
data.mean()

30.733333333333334

In [15]:
# square root
np.sqrt(data)

array([[ 5.65685425,  5.38516481,  5.38516481,  6.        ,  5.47722558,
         5.74456265,  5.        ,  5.83095189,  5.65685425,  5.47722558],
       [ 5.29150262,  5.        ,  6.        ,  5.56776436,  5.38516481,
         5.56776436,  5.38516481,  5.47722558,  5.91607978,  5.65685425],
       [ 5.38516481,  5.19615242,  5.19615242,  5.91607978,  5.65685425,
         5.47722558,  5.56776436,  5.83095189,  5.19615242,  5.83095189]])

In [16]:
# max 
data.max()

36

In [17]:
data.min()

25

## Linear algebra

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.


** There are two ways**.
We can either use the **np.dot** function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: OR
Use multiplication which applies to matrix-matrix.

### Matrix algebra

There are two ways. We can either use the **np.dot** function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments:

* **np.dot**   $\Rightarrow$ For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors.

* **np.matmul** $\Rightarrow$  Matrix product of two arrays.


In [18]:
#  create an array of  a and b
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])

In [19]:
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [20]:
# Or you can write
a.dot(b)

array([[4, 1],
       [2, 2]])

In [21]:
a*b

array([[4, 0],
       [0, 2]])

In [22]:
# create a vector v
v = np.array([5, 2.5])
np.dot(a, v)

array([ 5. ,  2.5])

In [ ]:
a*b

In [23]:
# inner product
v.T * v

array([ 25.  ,   6.25])

## Matrix computations

#### Inverse

An *identity matrix* is a matrix that does not change any vector when we multiply that vector by that matrix denoted as $I_n \in  \mathbb{R}^{n \times n}$.

The matrix inverse of $A$ is denoted as $A^{-1}$, is defined as the matrix such that:
$$ \mathbf{A A^{-1} = I_n} $$


In [24]:
np.linalg.inv(a)

array([[ 1.,  0.],
       [ 0.,  1.]])

### Determinant
The determinant of a square matrix $\mathbf{A}$ is often denoted $\mid\mathbf{A}\mid$ and is a quantity often used in linear algebra. 

In [25]:
np.linalg.det(a)

1.0

## Linear Equations

A system of linear equations is given as $$ \mathbf{Ax =b}$$ where $A \in \mathbb{R}^{m \times n}$ is a known matrix, $b \in \mathbb{R}^{m}$ is a known vector, and $x \in \mathbb{R}^n$ is a
vector of unknown variables. We can solve for $\mathbf{x}$ by following steps:

\begin{align*}
Ax &=b \\
A^{-1} Ax &= A^{-1} b \\
I_n x &=A^{-1} b \\
x &=A^{-1} b
\end{align*}


**For example**, let solve these equations: 

\begin{eqnarray*} x + 3y + 5z & = & 10 \\
                   2x + 5y + z & = & 8  \\
                   2x + 3y + 8z & = & 3
 \end{eqnarray*}

In [26]:
# In matrix notation: 
A = np.array([[1., 3., 5.],
               [2., 5., 1.],
               [2., 3., 8.]])

In [27]:
b = np.array([10,8,3])

In [29]:
#using a matrix inverse
x = np.linalg.solve(A, b)
#x = np.dot(np.linalg.inv(A),b)
print(x)

[-9.28  5.16  0.76]


In [ ]:
## Or use 
x = np.linalg.solve(A, b)
print(x)

### Numpy Exercise

* Generate a matrix with 10 rows and 50 columns, elements being drawn from normal distribution $\mathcal{N}(1, 10)$. Specify random seed to make the result reproducible.
* Normalize the above matrix: subtract from each column its mean and divide by the standard deviation. I suggest np.mean, np.std with axis parameter.
* Define function scale which takes a vector of numbers and brings them to the range from 0 to 1:

$$ scale(x)=\frac{x_i - min(x)}{max(x) - min(x)}$$

In [30]:
np.random.seed(77)
mu, sigma = 1, 10 # mean and standard deviation
gaussian = np.random.normal(mu, sigma, (50,10))

In [31]:
gaussian.shape

(50, 10)

In [34]:
gaussian.max()

30.080490212045813

In [32]:
def normalize(A):
    A = (A - np.mean(A, axis=0)) / np.std(A, axis=0)
    return A

In [33]:
normalize_gaussian = normalize(gaussian)

In [35]:
normalize_gaussian.max()

3.1271037018333141