

## Numpy Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.


To use numpy need to import the numpy module as follows.

In [1]:
import numpy as np # naming import convention


## Creating numpy arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples or
* using functions that are dedicated to generating numpy arrays, such as arange, linspace, etc.

### From lists
For example, to create new vector and matrix arrays from Python lists we can use the numpy.array function.

In [ ]:
v = np.array([1,2,3,4])
v

In [ ]:
# get dimension of an array
v.ndim

In [ ]:
#get shape of an array
v.shape

# or you may use np.shape(v)

In [ ]:
M = np.array([[1, 2], [3, 4]])
M

In [ ]:
M.ndim

In [ ]:
T = np.array([[[1,2,4, -1],
              [-2,0,0, 2],
             [-3,0,2, 3]]])

In [ ]:
T.ndim

In [ ]:
T.shape

In [ ]:
T

The v,  M, and T objects are both of the type ndarray that the numpy module provides.The difference between them is only their shapes and dimensions.

Equivalently, we can get information about the size of the two ndarrays, namely the total number of elements in the array.

In [ ]:
M.size

In [ ]:
v.size

In [ ]:
T.size

Similary we can use python list to create numpy matrix

In [ ]:
c = np.matrix([[0,2,4],
               [1,5,-2],
               [1,0,1]])
c

## Note: 
Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional.
The main advantage of numpy matrices is that they provide a convenient notation for matrix multiplication: if a and b are matrices, then a*b is their matrix product.

### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists.
Instead we can use one of the many functions in numpy that generates arrays of different forms.

Some of the more common are:

* np.arange;
* np.linspace;
* np.logspace;
* np.diag;
* np.zeros;
* np.ones;
* np.empty;


#### np.arange

In [ ]:
#Evenly spaced array (arange)
a = np.arange(10) # 0 .. n-1  (!)
a

In [ ]:
b = np.arange(0, 2, 0.5) # start, end (exclusive), step
b

In [ ]:
np.arange(-1,0,0.1)

#### np.linspace and np.logspace

In [ ]:
# using linspace, both end points **ARE included**
c = np.linspace(0, 1, 10)
c

In [ ]:
# equally spaced values on a logarithmic scale, use logspace.
d = np.logspace(0,1,5) 
d

In [ ]:
np.logspace(0, 4, 5, base=2) # specify the logarithmic base, by default is base 10

### Use common array

In [ ]:
# Create a 4x4 array with integer zeros
a = np.zeros((4, 4))
print(a)

In [ ]:
# Create a 4x4 array with integer 1
b = np.ones((4, 4))
print(b)

## Random Number Generation

### np.random.rand & np.random.randn

It is often useful to create arrays with random numbers that follow a specific distribution. The np.random module contains a number of functions that can be used to this effect.

In [2]:
# uniform random numbers in [0,1]
np.random.rand(5)

array([ 0.7927866 ,  0.20844588,  0.03951385,  0.56286105,  0.82764497])

In [3]:
# standard Gaussian distribution  with mean 0 and standard deviation 0.1
mu, sigma = 0, 0.1 # mean and standard deviation
size=10
np.random.normal(mu, sigma, size)

array([-0.05237081, -0.01117362,  0.06815517, -0.19094191,  0.01758955,
       -0.06099876,  0.09898422,  0.03073307, -0.12913406, -0.14306064])

### Random seed

The seed is for when we want repeatable results

In [4]:
np.random.seed(77)
np.random.rand(5)

array([ 0.91910903,  0.6421956 ,  0.75371223,  0.13931457,  0.08731955])

### Exercise

* Create an array [-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1] without typing the values by hand
* Generate a NumPy array of 1000 random numbers sampled from a Poisson distribution, with parameter $\lambda=5$. 
**Hint use: np.random.poisson(lambda, size)**

# Indexing and slicing 


We can index elements in an array using the square bracket and indices. The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):

In [2]:
 # Create an array of temp sensor data for seven day
np.random.seed(77)
tempData = np.random.randint(25,37, size=10)
print(tempData)

[32 29 29 36 30 33 25 34 32 30]


In [3]:
#print the first sensor data
print(tempData[0])

32


In [4]:
#print the sensor data between index 3 and 7
print(tempData[3:7])

[36 30 33 25]


### Note that the last index is not included! :

In [5]:
#print the last three data

print(tempData[7:])

[34 32 30]


In [7]:
# The first three sensor data
print(tempData[:3])

[32 29 29]


## Multidimensional array
Multidimensional array behaves like a dataframe or matrix (i.e. columns and rows)

In [8]:
#Create an array of rtemp sensor  data for three day
tempData2 = np.random.randint(25.5,37.5, size=10)
tempData3 = np.random.randint(26.5,36.5, size=10)
data = np.array([tempData, tempData2, tempData3])
print(data)

[[32 29 29 36 30 33 25 34 32 30]
 [28 25 36 31 29 31 29 30 35 32]
 [29 27 27 35 32 30 31 34 27 34]]


In [10]:
# View the first column of the array
data[:,1]

array([29, 25, 27])

In [12]:
# View the first row of the array
data[1,]

array([28, 25, 36, 31, 29, 31, 29, 30, 35, 32])

In [13]:
# View the first two row
data[:2,]

array([[32, 29, 29, 36, 30, 33, 25, 34, 32, 30],
       [28, 25, 36, 31, 29, 31, 29, 30, 35, 32]])

In [14]:
#View the first  data
data[0,0]

32

In [15]:
# Property of this array
print('Data type                :', data.dtype)
print('Total number of elements :', data.size)
print('Number of dimensions     :', data.ndim)
print('Shape (dimensionality)   :', data.shape)
print('Memory used (in bytes)   :', data.nbytes)

Data type                : int32
Total number of elements : 30
Number of dimensions     : 2
Shape (dimensionality)   : (3, 10)
Memory used (in bytes)   : 120


## Shape Manipulation
Changing the shape of an array. An array has a shape given by the number of elements along each axis:
The shape of an array can be changed with various commands:

In [16]:
#consider data shape
data.shape

(3, 10)

In [17]:
#np.ravel: Return a contiguous flattened array.
x = data.ravel()

In [18]:
x.shape

(30,)

In [19]:
x

array([32, 29, 29, 36, 30, 33, 25, 34, 32, 30, 28, 25, 36, 31, 29, 31, 29,
       30, 35, 32, 29, 27, 27, 35, 32, 30, 31, 34, 27, 34])

In [20]:
# np.reshape: Gives a new shape to an array without changing its data.
x.reshape((6, 5))

array([[32, 29, 29, 36, 30],
       [33, 25, 34, 32, 30],
       [28, 25, 36, 31, 29],
       [31, 29, 30, 35, 32],
       [29, 27, 27, 35, 32],
       [30, 31, 34, 27, 34]])

## Stacking together different arrays

Several arrays can be stacked together along different axes:

In [21]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

In [22]:
print(a)

[[ 4.  1.]
 [ 0.  2.]]


In [23]:
print(b)

[[ 0.  7.]
 [ 0.  4.]]


In [24]:
# Stack arrays in sequence vertically (row wise).
np.vstack((a, b))

array([[ 4.,  1.],
       [ 0.,  2.],
       [ 0.,  7.],
       [ 0.,  4.]])

In [25]:
# Stack arrays in sequence horizontally (column wise).
np.hstack((a,b))

array([[ 4.,  1.,  0.,  7.],
       [ 0.,  2.,  0.,  4.]])

## Load Data

To load data from text file use: **np.loadtxt()**

In [26]:
data_csv= np.loadtxt("data/txtdata.csv")

In [27]:
data_csv.shape

(74,)

In [26]:
len(data_csv)

74

In [29]:
data_csv

array([ 13.,  24.,   8.,  24.,   7.,  35.,  14.,  11.,  15.,  11.,  22.,
        22.,  11.,  57.,  11.,  19.,  29.,   6.,  19.,  12.,  22.,  12.,
        18.,  72.,  32.,   9.,   7.,  13.,  19.,  23.,  27.,  20.,   6.,
        17.,  13.,  10.,  14.,   6.,  16.,  15.,   7.,   2.,  15.,  15.,
        19.,  70.,  49.,   7.,  53.,  22.,  21.,  31.,  19.,  11.,  18.,
        20.,  12.,  35.,  17.,  23.,  17.,   4.,   2.,  31.,  30.,  13.,
        27.,   0.,  39.,  37.,   5.,  14.,  13.,  22.])